{
 "title": "nb messages dernières 24h",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Alerts on Text",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 0 },
   "targets": [
    { "expr": "messages_24h_nb_alerts", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Messages dernières 24h",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "messages_24h_nb", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "All Messages",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iris_interop_messages", "legendFormat": "{{host}}" }
   ]
  }
 ]
}