services:
  iris:
    build:
      context: ./IRIS
      dockerfile: Dockerfile
    init: true
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    volumes:
    - type: bind
      source: ./IRIS
      target: /IRIS
    - type: bind
      source: ./data
      target: /data
    # command: -a /IRIS/configure.sh
    ports:
      - 29720:1972
      - 28000:52773
  notebook:
    build: 
      context: notebook
      dockerfile: dockerfile
    ports:
      - "28001:8888"
    volumes:
      - ./notebook/Notebooks:/Notebooks
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/Notebooks"