/// Created from: /IRIS/SDC/IEEE11073-20701-Services.wsdl
Class SDC.ns1.SetComponentStateOperationDescriptor Extends SDC.ns1.AbstractSetStateOperationDescriptor [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "http://standards.ieee.org/downloads/11073/11073-10207-2017/participant";

Parameter XMLNAME = "SetComponentStateOperationDescriptor";

Storage Default
{
<Type>%Storage.Serial</Type>
}

}
