{
 "title": "Interop - messages",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Messages HL7",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iris_interop_messages{host=\"source HL7 FILE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message HL7 en erreur",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iris_interop_messages{host=\"HL7v2 messages erreurs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "messages",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "iris_interop_messages{id=\"IRISAPP\", host!=\"Ens.Actor\", host!=\"Ens.ScheduleHandler\", host!=\"Ens.ProductionMonitorService\", host!=\"JDBC Gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}