{
 "title": "InterSystems IRIS for Health",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values({instance=\"host.docker.internal:28000\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Databases latencies",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iris_db_latency", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Database Free Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iris_db_free_space", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "targets": [
    { "expr": "iris_cpu_usage", "legendFormat": "CPU Utilization" }
   ]
  },
  {
   "title": "Cache Efficiency",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iris_cache_efficiency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database Reads",
   "type": "stat",
   "description": "## Physical Reads\n\nThe number of database blocks (8K and other sizes [if any]) read from disk per second. \n\nThis is the Disk I/O read activity--notice that on active systems there is always non-zero read data.\n",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iris_phys_reads_per_sec{instance=\"host.docker.internal:28000\"}",
     "legendFormat": "Database Reads"
    }
   ]
  },
  {
   "title": "Total Pri Jnl Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iris_jrn_size{id=\"primary\",instance=\"host.docker.internal:28000\"}"
    }
   ]
  },
  {
   "title": "IRIS Database Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iris_db_latency{id=\"IRISSYS\", instance=\"host.docker.internal:28000\"}",
     "legendFormat": "Database Latency"
    }
   ]
  },
  {
   "title": "WIJ Free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iris_jrn_free_space{id=\"WIJ\",instance=\"host.docker.internal:28000\"}"
    }
   ]
  },
  {
   "title": "IRIS Disk Percent",
   "type": "bargauge",
   "description": "This shows disk percentage full for the disk that IRIS is installed on \n\n**Note:** GB remaining is much more important!",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iris_disk_percent_full{id=\"IRISSYS\",instance=\"host.docker.internal:28000\"}",
     "legendFormat": "IRIS Disk Percent"
    }
   ]
  },
  {
   "title": "Pri Jnl Free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iris_jrn_free_space{id=\"primary\",instance=\"host.docker.internal:28000\"}"
    }
   ]
  },
  {
   "title": "IRIS Disk Remaining",
   "type": "stat",
   "description": "MB remaining is much more important than %!",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iris_directory_space{id=\"IRISSYS\",instance=\"host.docker.internal:28000\"}",
     "legendFormat": "IRIS Space Remaining"
    }
   ]
  },
  {
   "title": "Glorefs",
   "type": "timeseries",
   "description": "## Glorefs\n\nGlobal References per second is the number of times a data element was accessed whether that was from disk or from database cache. \n\nThis is a good indication of \"activity\"--high numbers mean high activity. \n\nAnother way of looking at GloRefs is as an indicator of database transaction rate.\n\n## Look for\n\n__No Hard limits__\n  \nLook for unusual deviations from baselines. \n\nLower than normal may indicate struggling with a resource - CPU, IO, or block contention, network\n\nCorrelate with disk IO\n\nHigh global references at the same time as a low database cache hit ratio (Cache Efficiency)  during peak hours will increase the physical read rate for database references.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "iris_glo_ref_per_sec{instance=\"host.docker.internal:28000\"}",
     "legendFormat": "Glorefs"
    },
    {
     "expr": "iris_glo_ref_rem_per_sec{instance=\"host.docker.internal:28000\"}",
     "legendFormat": "Remote Glorefs"
    }
   ]
  },
  {
   "title": "Global Updates",
   "type": "timeseries",
   "description": "## Global updates \n\nLocal SET and KILL",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "iris_glo_update_per_sec{instance=\"host.docker.internal:28000\"}",
     "legendFormat": "Global Updates"
    }
   ]
  },
  {
   "title": "System Alerts",
   "type": "stat",
   "description": "The number of alerts posted to the messages log since system startup.",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iris_system_alerts{instance=\"host.docker.internal:28000\"}"
    }
   ]
  },
  {
   "title": "Recent Alerts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iris_system_alerts_new", "legendFormat": "__auto" }
   ]
  }
 ]
}